#!/bin/sh -e
# Usage: zk new <title>
# Summary: create a new entry

title=$(echo "$@" | sed 's/ /-/g')

if [[ $title == "" ]]; then
  echo "Name is missing" >&2
  exit 1
fi

timestamp=$(date +"%Y-%m-%d-%H-%M")

file="$ZK_PATH/$timestamp-$title.md"

$EDITOR -c ":set autochdir" "$file"
